# Generated by Django 3.1.6 on 2021-02-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
