# Generated by Django 3.1.6 on 2021-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210222_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approvals',
            field=models.BooleanField(default=False),
        ),
    ]
