# Generated by Django 3.1.6 on 2021-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approvals',
            field=models.BooleanField(default=True),
        ),
    ]
